packages:
  - "!sponsors"
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true
catalog:
  vite-plus: ^0.1.13
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  esbuild: 0.28.0
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
verifyDepsBeforeRun: install
