packages:
  - "!sponsors"
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true
catalog:
  vite-plus: ^0.2.0
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  esbuild: 0.28.1
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
verifyDepsBeforeRun: install
minimumReleaseAgeExclude:
  - "@oxc-minify/*"
  - "@oxc-parser/*"
  - "@oxc-project/*"
  - "@oxfmt/*"
  - "@oxlint-tsgolint/*"
  - "@oxlint/*"
  - "@rolldown/*"
  - "@tsdown/*"
  - "@vitejs/devtools"
  - "@vitest/*"
  - "@voidzero-dev/*"
  - oxc-minify
  - oxc-parser
  - oxfmt
  - oxlint
  - oxlint-tsgolint
  - rolldown
  - tsdown
  - vite
  - vite-plus
  - vitest
  - void@0.10.8
