name: Release

permissions: {}

on:
  push:
    branches:
      - release-pr
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
      issue-number:
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: oxc-project/oxc
          ref: main
          path: oxc
          persist-credentials: false

      - name: Install Tools
        uses: taiki-e/install-action@fd0f63e180a477d7434580b6d80817978b9ff2b8 # v2.70.1
        with:
          tool: just

      - run: rm -rf src/docs/guide/usage/linter/rules
      - run: cd oxc && just website ..
      - run: rm -rf oxc

      - uses: voidzero-dev/setup-vp@e34774bccb4e7d7f2e23514ca980177a71425e43 # v1.5.0
      - run: vp run fmt

      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.OXC_BOT_PAT }}
          commit-message: Release ${{ inputs.version }}
          branch: release
          branch-suffix: timestamp
          title: Release ${{ inputs.version }}
          body: From https://github.com/oxc-project/oxc/pull/${{ inputs.issue-number }}
          assignees: camc314
          base: main
