name: Release

permissions: {}

on:
  push:
    branches:
      - release-pr
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
      issue-number:
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: oxc-project/oxc
          ref: main
          path: oxc
          persist-credentials: false

      - name: Install Tools
        uses: taiki-e/install-action@7769b73c2ec98c38dfcf2e18c83cfd4880c038c1 # v2.75.27
        with:
          tool: just

      - run: rm -rf src/docs/guide/usage/linter/rules
      - run: cd oxc && just website ..
      - run: rm -rf oxc

      - uses: voidzero-dev/setup-vp@4f5aa3e38c781f1b01e78fb9255527cee8a6efa6 # v1.8.0
      - run: vp run fmt

      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: Release ${{ inputs.version }}
          branch: release
          branch-suffix: timestamp
          title: Release ${{ inputs.version }}
          body: From https://github.com/oxc-project/oxc/pull/${{ inputs.issue-number }}
          assignees: camc314
          base: main
