name: Release

permissions: {}

on:
  push:
    branches:
      - release-pr
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
      issue-number:
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: oxc-project/oxc
          ref: main
          path: oxc
          persist-credentials: false

      - name: Install Tools
        uses: taiki-e/install-action@b8cecb83565409bcc297b2df6e77f030b2a468d5 # v2.82.0
        with:
          tool: just

      - run: rm -rf src/docs/guide/usage/linter/rules
      - run: cd oxc && just website ..
      - run: rm -rf oxc

      - uses: voidzero-dev/setup-vp@2dec1e33f4ab2c6d5bce1b0c4607961bb1a3f7a1 # v1.12.0
      - run: vp run fmt

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: Release ${{ inputs.version }}
          branch: release
          branch-suffix: timestamp
          title: Release ${{ inputs.version }}
          body: From https://github.com/oxc-project/oxc/pull/${{ inputs.issue-number }}
          assignees: camc314
          base: main
